# Librerías que usaremos para el curso:
**SciPy:** Agrupa muchas funciones relevantes para los cálculos numéricos.

**NumPy:** Proporciona funciones específicas para cálculos vectoriales y matriciales.

**SymPy:** Abarca todas las funciones necesarias para cálculos simbólicos.

**Matplotlib:** Contiene herramientas para trazados 2D y 3D (similares a los de MATLAB).

**Pandas:** Específica para gestión y análisis de datos.

## El módulo NumPy:

Sea el sistema:
$$4x+3y = 20 \\
-5x+9y = 26$$

En forma matricial:
$$A_x=b0$$
donde
$$
A = \begin{pmatrix}
         4 & 3 \\
        -5 & 9 
    \end{pmatrix} \quad
x = \begin{pmatrix}
         x \\
         y
    \end{pmatrix},\quad     
b = \begin{pmatrix}
         20 \\
         26
    \end{pmatrix}
$$
La solución está dada por 
$$ x = A^{-1}b$$
pseudocódigo para la solución:

In [1]:
A = [[4 3][-5 9]]
X = [[x][y]]
B = [[20][26]]
X = inverse(A).B

SyntaxError: invalid syntax (<ipython-input-1-4388284ca37c>, line 1)

Código correcto con **NumPy:**

In [6]:
import numpy as np
Alist=[[4,3],[-5,9]]
A=np.array(Alist)
print(A)

[[ 4  3]
 [-5  9]]


In [8]:
inv_A=np.linalg.inv(A)
print(inv_A)

[[ 0.17647059 -0.05882353]
 [ 0.09803922  0.07843137]]


In [9]:
B = np.array([20,26])
print(B)

[20 26]


In [11]:
X=np.dot(inv_A,B)
print(X)

[2. 4.]


In [12]:
U = np.array([11,12,13,14])
V = np.array([25,26,27,28])
W = U+V
print(W)

[36 38 40 42]


In [13]:
A = np.array([1,2,3])
B = 3*A
print(B)

[3 6 9]
